package com.bdd.employee.itegration.department;

import com.bdd.employee.configurations.SecurityConfiguration;
import com.bdd.employee.departments.Department;
import com.bdd.employee.departments.DepartmentController;
import com.bdd.employee.facade.JsonMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.util.Base64Utils;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

public class DepartmentSystem extends com.bdd.employee.facade.DepartmentSystem {
    protected MockMvc mockMvc;

    public DepartmentSystem(MockMvc mockMvc) {
        this.mockMvc = mockMvc;
    }

    @Override
    public Department createDepartment(Department department) throws Exception {
        JsonMapper<Department> jsonMapper = new JsonMapper<>();
        MvcResult mvcResult = this.mockMvc
                .perform(
                        post(DepartmentController.URL)
                        .header(HttpHeaders.AUTHORIZATION,
                                "Basic " + Base64Utils.encodeToString((SecurityConfiguration.ADMIN_USER + ":" + SecurityConfiguration.ADMIN_PASSWORD).getBytes()))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(jsonMapper.toString(department))
                        .accept(MediaType.APPLICATION_JSON)
                )
                .andExpect(status().isCreated())
                .andExpect(MockMvcResultMatchers.jsonPath("$.departmentName").value(department.getDepartmentName()))
                .andReturn();

        String content = mvcResult.getResponse().getContentAsString();
        return jsonMapper.toObject(content, Department.class);
    }

    @Override
    public Long getAutoGeneratedId() {
        return null;
    }
}
