package com.bdd.employee.facade;

import com.bdd.employee.departments.Department;

public abstract class DepartmentSystem {
    public abstract Department createDepartment(Department department) throws Exception;
    public abstract Long getAutoGeneratedId();
}

